---
- name: Docker run playbook
  hosts: back_end
  remote_user: ec2-user
  become: true

  tasks:
    - name: Installing Docker
      yum:
        name: docker
        state: present

    - name: Enable and start docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Pull the latest Docker image
      command: docker pull m95kandan/xpb-node-app:latest
      register: docker_image_pulled
      changed_when: docker_image_pulled.rc == 0

    - name: Run Docker container
      docker_container:
        name: node-app
        image: m95kandan/node-app:latest
        ports:
          - "80:80"
        restart_policy: always
      when: docker_image_pulled.changed or docker_image_pulled is skipped
