---
- name: Docker run playbook
  hosts: back_end
  remote_user: ec2-user
  become: true

  tasks:
    - name: Installing Docker
      yum:
        name: docker
        state: present

    - name: Enable and start docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Run Portainer agent container
      docker_container:
        name: portainer_agent
        image: portainer/agent:2.19.4
        ports:
          - "9001:9001"
        restart_policy: always
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/var/lib/docker/volumes:/var/lib/docker/volumes"

    - name: Pull the latest Docker image
      command: docker pull m95kandan/xpb-node-app:latest
      register: docker_image_pulled
      changed_when: docker_image_pulled.rc == 0

    - name: Stop and remove existing container if it exists
      shell: docker rm -f node-app
      ignore_errors: yes

    - name: Run Docker container
      docker_container:
        name: node-app
        image: m95kandan/xpb-node-app:latest
        ports:
          - "80:80"
        restart_policy: always
      when: docker_image_pulled.changed or docker_image_pulled is skipped
