---
- name: Docker run playbook
  hosts: back_end
  remote_user: ec2-user
  become: true

  tasks:
    - name: Installing Docker
      yum:
        name: docker
        state: present

    - name: Enable and start docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Run Docker container
      docker_container:
        name: node-app-1
        image: "{{ dockerhub_repository }}"
        ports:
          - "80:80"
        restart_policy: always
